### ISSUE TITLE
Issue: 8.ui_main.sh

### ISSUE THREAD

**Issue by sn1p3r46** [satya164/fedy#101]
Hi! First i have to say GREAT JOB Bro! Thank you!

So from today when I start Fedy and select one of the radio button it loops again in the main first window..  Console output is: 
```
/usr/share/fedy/run/8.ui_main.sh: eval: line 8: syntax error near unexpected token `|'
/usr/share/fedy/run/8.ui_main.sh: eval: line 8: `|'
```
Is it a known issue?

I tried also to copy and replace the github 8.ui_main.sh file, but it seems the same..
I never opened this file, never. 

Ty in advice!

**Comment by satya164** [comment]
The issue is no longer relevant in the current master.
