### ISSUE TITLE
Cannot use more than 1 time.

### ISSUE THREAD

**Issue by arayaq** [satya164/fedy#119]
After the first intall with Fedy (Numix Themes) the app loops at the initial screen with the following error on console `** (Fedy:26855): WARNING **: atk-bridge: Couldn't listen on dbus server: Failed to bind socket "/root/.cache/at-spi2-socket-26855": No such file or directory` .

When running a task from console I get the [this](http://fpaste.org/164619/) log.

**Comment by ntpeters** [comment]
I'm having the exact same issue.

Here is my log as well: http://fpaste.org/164882/42016758/

**Comment by satya164** [comment]
Seems to be some issue with yad. For now, you can try running Fedy from command line. Try the following,

    fedy --help

**Comment by tijptjik** [comment]
Same issue here. As per the instructions on the main site

```bash
fedy -e list
```
gives you a list of all available functionality, and you can then just run

```bash
fedy --exec COMMAND
```
to get the regular functionality out of fedy.

**Comment by satya164** [comment]
The issue is no longer relevant in the current master.
