### ISSUE TITLE
RPM hosting error

### ISSUE THREAD

**Issue by decimalst** [satya164/fedy#122]
Hello,
I am a user of the fedy script on Fedora 21. First of all, thank you, because it's an incredibly useful piece of software. 
Secondly, the rpm hosting appears to be giving an error: when trying to download either the Fedora 20 or 21 rpm packages off of http://mirror.switch.ch/ftp/mirror/opensuse/repositories/home:/satya164:/fedy/Fedora_20/noarch/fedy-3.2.2-3.2.noarch.rpm I recieve an error saying object not found. This also causes the fedy-installer script to fail when running, when yum says that the package does not exist.
By cloning the git repo, I was able to run the script without issue, however.

**Comment by sjourdan** [comment]
Same issue here, looks like a problem with the switch.ch mirror.
The RPM file is available from OpenSuse directly [here](http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_21/noarch/fedy-3.2.2-3.1.noarch.rpm).

**Comment by satya164** [comment]
We'll soon move it to our own repo.

**Comment by thesteve0** [comment]
So there is a file icon http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_21/noarch/  but there is no file. Is there anywhere else to get the rpm so I can do a manual install?

**Comment by satya164** [comment]
Fedy has moved to ozon repos and this is no longer an issue.
