### ISSUE TITLE
Moka theme failed to install

### ISSUE THREAD

**Issue by alsosabot13** [satya164/fedy#124]
Here is the output of the script when it tried to install moka theme on Fedora 21.

No package moka-icon-theme available.
Error: Nothing to do
Trying with Fedora 20 repo
Loaded plugins: fastestmirror, langpacks
http://download.opensuse.org/repositories/home%3A/snwh%3A/moka-gtk-theme/Fedora_20/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/snwh%3A/moka-icon-theme/Fedora_20/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Loading mirror speeds from cached hostfile
 * fedora: mirror.globo.com
 * rpmfusion-free: mirror.us.leaseweb.net
 * rpmfusion-free-updates: mirror.us.leaseweb.net
 * rpmfusion-nonfree: mirror.us.leaseweb.net
 * rpmfusion-nonfree-updates: mirror.us.leaseweb.net
 * updates: mirror.globo.com

**Comment by cereda** [comment]
IIRC, the Moka Project has now its own repository set at `http://mokaproject.com/packages/rpm/moka-stable.repo` (that's how mine is configured in my machine). Maybe `fedy` could be updated in order to include this new location. `:)`

**Comment by Rohan62442** [comment]
![screenshot from 2015-02-03 22 57 32](https://cloud.githubusercontent.com/assets/8509827/6025391/1cb08c9e-abf8-11e4-9b3e-38abb03f0829.png)

Same issue with me. It told me that the repositories couldn't be added and switched to fedora 20 repositories. Then it told me that neither of the two packages could be found.

**Comment by Rohan62442** [comment]
![screenshot from 2015-02-08 19 48 44](https://cloud.githubusercontent.com/assets/8509827/6096856/8ab00cf6-afcc-11e4-9e20-2ffa9fa17350.png)
Still getting this. Now it seems fedy can't find the packages.

**Comment by satya164** [comment]
These issues keep happening with OBS. Packages on the repo have to be rebuilt for it to be fixed.

@snwh can you fix this?

**Comment by Rohan62442** [comment]
I think that the primary mirror used to download the file gives a 404 error. I tried to manually download it from other mirror and that worked.

**Comment by snwh** [comment]
Yeah, I've migrated it all over to OBS.
