### ISSUE TITLE
Install Viber

### ISSUE THREAD

**Issue by valentt** [satya164/fedy#131]
Hi, please add Viber as software install.

Viber is available from rpm - http://download.cdn.viber.com/desktop/Linux/viber.rpm

**Comment by satya164** [comment]
Can you send a pull request? Should be an easy thing to add. Code will very similar to the google chrome installer code.

**Comment by Rohan62442** [comment]
This issue can be closed. The pull request (#140) has been merged.

**Comment by satya164** [comment]
You might wanna check out the `next` branch. There are major changes!

**Comment by Rohan62442** [comment]
I'm doing that right now. How do I pull that branch to my local repo?

**Comment by satya164** [comment]
Just do the following,

```
git pull
git checkout next
./fedy
```

**Comment by satya164** [comment]
I'd suggest to go with the next branch and don't worry about master.
