### ISSUE TITLE
Fedora 21

### ISSUE THREAD

**Issue by wallacehermano** [satya164/fedy#145]
When open Fedy
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

** (Fedy:24238): WARNING **: atk-bridge: Couldn't listen on dbus server: Failed to bind socket "/root/.cache/at-spi2-socket-24238": No such file or directory

**Comment by DavidJameson** [comment]
I'm seeing this too --- no idea what it means.

**Comment by fedorahead** [comment]
Same here.

**Comment by satya164** [comment]
The issue is no longer relevant in the current master.
