### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by flyingrub** [satya164/fedy#146]
I have the fiber (~150Mbs) and my download speed is only arround 0.5mbs ...

**Comment by Rohan62442** [comment]
I doubt that this is a Fedy issue. Downloads are handled by wget or curl, and anyway they would depend on more factors than your fibre...

**Comment by satya164** [comment]
Yum is usually slow and doesn't pick the fastest mirror properly. Try to clean yum's cache.

On that note, we're switching to DNF in next version of Fedy.
