### ISSUE TITLE
Brackets error (libgcrypt.so.11)

### ISSUE THREAD

**Issue by wallacecmo86** [satya164/fedy#147]
Is missing in this lib installation. (Fedora 21 x86_64)

The problem can be solved by adding the installation of this:

https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-21-x86_64/compat-libgcrypt-1.5.3-4.fc21/compat-libgcrypt-1.5.3-4.fc21.x86_64.rpm

Sorry English, I used Google Translate.

**Comment by pranav-sharma** [comment]
+1 I also have this issue

**Comment by thelinuxfr** [comment]
+1 :)

**Comment by satya164** [comment]
Can you check with the [next branch](https://github.com/satya164/fedy/tree/next) if the issue still persists?
