### ISSUE TITLE
Insecure URLs in fedy-installer script

### ISSUE THREAD

**Issue by p-e-w** [satya164/fedy#148]
It's laudable that the instructions on http://satya164.github.io/fedy/ feature a HTTPS URL, but in https://github.com/satya164/fedy/blob/gh-pages/fedy-installer the repo URLs are just HTTP again.

Effectively, this means that people who follow the instructions run code from an insecure connection **as root**, which is a security risk. See also http://curlpipesh.tumblr.com/.

**Comment by satya164** [comment]
I don't see why http repo URLs should be a concern. All repos on your system are already http.

**Comment by p-e-w** [comment]
The problem is [this line](https://github.com/satya164/fedy/blob/gh-pages/fedy-installer#L17), which obtains the signing key via HTTP. Thus a MITM attacker could first replace the key the user gets, and then inject malicious packages signed with the replacement key, passing the GPG check.

This is *not* the case with Fedora's standard repos: While the packages are downloaded over HTTP, they are verified using the signing keys that come bundled with every Fedora installation.

As long as the signing key is not obtained securely, the packages might as well not be signed at all. RPM Fusion has the same problem, but they do at least [publish their keys on MIT's keyserver](http://rpmfusion.org/keys), from where they can be obtained securely, though RPM Fusion does not provide instructions for that.

*(What's worse, I now notice that although a signing key is present in the repo metadata, the signature check is [intentionally disabled when installing fedy](https://github.com/satya164/fedy/blob/gh-pages/fedy-installer#L29) – [even for the coreutils](https://github.com/satya164/fedy/blob/gh-pages/fedy-installer#L31)! Why?)*

**Comment by satya164** [comment]
Fedy is being rewritten, it's still have a new repo and no more ignoring signing keys. Check the next branch.
