### ISSUE TITLE
Add Fedora 22 support

### ISSUE THREAD

**Issue by ghost** [satya164/fedy#150]
Hi, the fedora 22 repository for Fedy doesn't exist:

```
Failed to synchronize cache for repo 'fedy' from 'http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_22/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
```

**Comment by spaceisstrange** [comment]
Happens to me too, hope it's updated soon.

**Comment by nilgradisnik** [comment]
+1 Keep up the good work.

**Comment by diegobfernandez** [comment]
F22 is almost there.
Any updates?

**Comment by satya164** [comment]
Fedy is being rewritten. I'll try to finish it up ASAP.

**Comment by satya164** [comment]
The Fedora 22 repo has been added. But some packages might not work until their maintainers update the repos.

**Comment by santiagon610** [comment]
@satya164 - Just tested on F22 beta, with my normal list of stuff that I use, and it seems to work well. The new UI is beautiful, great job!

**Comment by nilgradisnik** [comment]
Tested on Fedora 22, works flawlessly. Love the new UI as well :+1:

**Comment by satya164** [comment]
Cool then :)

**Comment by metabsd** [comment]
fedy numix option don't work. Normal ?? I use Fedora 22. Thx!
