### ISSUE TITLE
Google Chrome update

### ISSUE THREAD

**Issue by MircoT** [satya164/fedy#152]
I had this error when I tried to upgrade the system:

```Public key for google-chrome-stable-42.0.2311.90-1.x86_64.rpm is not installed```

I found online that is a common problem when you install the package without adding the public key. I don't know if it can be solved by adding the following line in the *google_chrome.sh* during the installation:

```rpm --import https://dl-ssl.google.com/linux/linux_signing_key.pub```

so I decided to open an issue to discuss the problem.

**Comment by satya164** [comment]
Thanks. Will add it to the script.
