### ISSUE TITLE
Better way of getting latest Brackets.

### ISSUE THREAD

**Issue by fa7ad** [satya164/fedy#157]
First we need #147 to be installed.
And to get the latest brackets, look to GitHub's releases API
Here's my current code snippet, most of it is ripped off of your script. 
change the standard commands back to fedy's format and maybe you can add this on master?
```bash
#!/bin/bash
echo "Removing old versions"
yum erase brackets -y
rm -rf /opt/brackets
echo "Getting latest version"
mkdir /tmp/brackets
cd /tmp/brackets
wget "https://api.github.com/repos/adobe/brackets/releases/latest" -O "brackets.json"
get=$(cat "brackets.json" | grep "64-bit.deb" | tail -n 1 | cut -d\" -f 4)
file=${get##*/}
wget "$get" -O "$file"
if [[ -f "$file" ]]; then
    echo "Installing deps"
    yum install atk ca-certificates cairo cups dbus expat fontconfig freetype gcc GConf2 gdk-pixbuf2 glib2 gtk2 libcurl libgcrypt libstdc++ libX11 libXcomposite libXdamage libXext libXfixes libXrandr libXrender nspr nss pango redhat-lsb wget xdg-utils -y
    echo "Installing files"
    mkdir -p "${file%.*}"
    ar p "$file" "data.tar.xz" | tar -C "${file%.*}" -xJf -
    cp -af "${file%.*}/opt/brackets" "/opt/"
    cp -af "${file%.*}/usr/bin/brackets" "/usr/bin/"
    cp -af "${file%.*}/usr/share/doc/brackets" "/usr/share/doc/"
    cp -af "${file%.*}/usr/share/menu/brackets.menu" "/usr/share/menu/"
    cp -af "${file%.*}/usr/share/icons/hicolor/scalable/apps/brackets.svg" "/usr/share/icons/hicolor/scalable/apps/"
    for icon in /opt/brackets/appshell*.png; do
        size="${icon##*/appshell}"
        xdg-icon-resource install --novendor --size "${size%.png}" "$icon" "brackets"
    done
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor > /dev/null 2>&1
    xdg-desktop-menu install --novendor /opt/brackets/brackets.desktop
    if [[ "$arch" = "32" ]]; then
        libdir="/usr/lib"
    elif [[ "$arch" = "64" ]]; then
        libdir="/usr/lib64"
    fi
    nss_files="libnspr4.so.0d libplds4.so.0d libplc4.so.0d libssl3.so.1d libnss3.so.1d libsmime3.so.1d libnssutil3.so.1d"
    for f in $nss_files; do
        target=$(echo $f | sed 's/\.[01]d$//')
        if [[ -f "$libdir/$target" ]]; then
            ln -snf "$libdir/$target" "/opt/brackets/$f"
        else
            show_err "$f not found in $libdir/$target"
        fi
    done
    [[ -f $libdir/libudev.so.1 ]] && ln -snf $libdir/libudev.so.1 $libdir/libudev.so.0
else
    echo "Failed! File doesn't exist"
fi
echo "Cleaning Up!"
rm -rf /tmp/brackets
```

**Comment by satya164** [comment]
In the [next branch](https://github.com/satya164/fedy/tree/next), Fedy uses copr repo to install Brackets, which is a much better way.

Closing this.

**Comment by fa7ad** [comment]
The copr releases are a bit behind on Brackets release version. Unless you're using a different copr than [this](https://copr.fedoraproject.org/coprs/jgillich/brackets/] .

Look at the screenshots
![screenshot from 2015-05-05 02 01 35](https://cloud.githubusercontent.com/assets/7447677/7461252/b90b6b36-f2ca-11e4-830c-12650079edd0.png)
![screenshot from 2015-05-05 02 00 13](https://cloud.githubusercontent.com/assets/7447677/7461255/c25f9dc4-f2ca-11e4-9dfb-7911ecfb78f6.png)

**Comment by satya164** [comment]
Hmm. You're right.

How about this one? - https://copr.fedoraproject.org/coprs/dacr/brackets/builds/

This one seems recent.

**Comment by fa7ad** [comment]
Sure, I don't see why not... if he keeps maintaining the copr.
Maybe you can use some kinda logic for using the git as a fallback. Say if the copr release and the git latest release vary by a x.**X**.x, then pull from the git otherwise use copr.

**Comment by satya164** [comment]
The primary reason of preferring copr is, packages are always cleaner to install and uninstall and risk-free. If I go with the script, then there is no reason to rely on packages from copr.

I'll change the copr to the new one, and let's see what happens.

**Comment by fa7ad** [comment]
Okay
I like Copr releases too, but many of these guys lose interest really soon, but okay... use this for now :+1:

**Comment by user501254** [comment]
In a perfect world Adobe Brackets team would build rpm packages. Till then let's use Copr.
