### ISSUE TITLE
Unable to uninstalll Oracle JRE/JDK on Fedora 21 x64

### ISSUE THREAD

**Issue by strasharo** [satya164/fedy#158]
http://fpaste.org/217800/65034143/

**Comment by strasharo** [comment]
Looks like it's trying to remove the packages with a incorrect name:
yum -y erase --skip-broken --setopt clean_requirements_on_remove=1 jre
yum -y erase --skip-broken --setopt clean_requirements_on_remove=1 jdk

The packages are actually names as follows:

[root@T14 ~] $ rpm -qi jdk1.8.0_31 
Name        : jdk1.8.0_31
Epoch       : 2000
Version     : 1.8.0_31
Release     : fcs
Architecture: x86_64
Install Date: Sun 15 Feb 2015 05:58:02 PM EET
Group       : Development/Tools
Size        : 231173532
License     : http://java.com/license
Signature   : (none)
Source RPM  : jdk1.8.0_31-1.8.0_31-fcs.src.rpm
Build Date  : Thu 18 Dec 2014 06:58:07 AM EET
Build Host  : sc11137389.us.oracle.com
Relocations : /usr/java 
Packager    : Java Software <jre-comments@java.sun.com>
Vendor      : Oracle Corporation
URL         : URL_REF
Summary     : Java Platform Standard Edition Development Kit
Description :
The Java Platform Standard Edition Development Kit (JDK) includes both
the runtime environment (Java virtual machine, the Java platform classes
and supporting files) and development tools (compilers, debuggers,
tool libraries and other tools).

The JDK is a development environment for building applications, applets
and components that can be deployed with the Java Platform Standard
Edition Runtime Environment.
[root@T14 ~] $ rpm -qi jre1.8.0_31 
Name        : jre1.8.0_31
Version     : 1.8.0_31
Release     : fcs
Architecture: x86_64
Install Date: Sun 15 Feb 2015 05:52:45 PM EET
Group       : Development/Tools
Size        : 100955184
License     : http://java.com/license
Signature   : (none)
Source RPM  : jre1.8.0_31-1.8.0_31-fcs.src.rpm
Build Date  : Thu 18 Dec 2014 06:55:31 AM EET
Build Host  : sc11137389.us.oracle.com
Relocations : /usr/java 
Packager    : Java Software <jre-comments@java.sun.com>
Vendor      : Oracle Corporation
URL         : URL_REF
Summary     : Java Platform Standard Edition Runtime Environment
Description :
The Java Platform Standard Edition Runtime Environment (JRE) contains
everything necessary to run applets and applications designed for the
Java platform. This includes the Java virtual machine, plus the Java
platform classes and supporting files.

The JRE is freely redistributable, per the terms of the included license.
[root@T14 ~] $

**Comment by satya164** [comment]
Please try the `next` branch. You should be able to uninstall from there.

**Comment by satya164** [comment]
Fixed in master
