### ISSUE TITLE
Fedy 4.0 rpm cant Create icons

### ISSUE THREAD

**Issue by isantolin** [satya164/fedy#161]
When i updated fedy, the updated package removed the icon (screenshot attached) and i could run Fedy just from terminal using the command: sudo sh /usr/bin/fedy

![captura de pantalla de 2015-05-17 15 47 33](https://cloud.githubusercontent.com/assets/264640/7671558/10b40cd6-fcac-11e4-87b4-70783e4fd9af.png)

**Comment by satya164** [comment]
I'll check when I get back home. Meanwhile can you try removing the package and directly installing this rpm? - http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-0.noarch.rpm

**Comment by satya164** [comment]
This should not be happening. Can you confirm?

**Comment by isantolin** [comment]
Corrected

**Comment by satya164** [comment]
@isantolin Great :D
