### ISSUE TITLE
Are there instructions on cleanly removing fedy?

### ISSUE THREAD

**Issue by Jobava** [satya164/fedy#163]
Are there instructions on cleanly removing fedy, in order to cleanly reinstall it at a later date?

Are there issues that can come from running the install script twice?

For some reason I had some trouble with fedy on a clean fedora 21 install.

**Comment by satya164** [comment]
There seems to be an error at my end. Will fix by tonight.

**Comment by satya164** [comment]
BTW you can remove Fedy with yum erase fedy

**Comment by satya164** [comment]
Also, no, there won't be any issue if you run the installer script twice.
