### ISSUE TITLE
Package fedy-4.0.0-0.noarch.rpm is not signed

### ISSUE THREAD

**Issue by ReclusiveGeek** [satya164/fedy#164]
Just got the following error when I did a yum update. I had you exclude the fedy repo before the system would update. I am using Fedoa 21.

**Comment by satya164** [comment]
Oops. My mistake. WIll sign it as soon as I get back home.

**Comment by satya164** [comment]
I've pushed a signed package to the repo. Can you try "dnf clean expre-metadata" and try installing it again?

**Comment by ReclusiveGeek** [comment]
That got further .... now I get 

Downloading packages:
No Presto metadata available for ozonos
fedy-4.0.0-0.noarch.rpm        FAILED                                          
http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-0.noarch.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ozonos clean metadata
Trying other mirror.
warning: /var/cache/yum/x86_64/21/ozonos/packages/ozon-repos-21-5.fc21.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID b8c0fc22: NOKEY
Public key for ozon-repos-21-5.fc21.noarch.rpm is not installed
(1/2): ozon-repos-21-5.fc21.noarch.rpm                      | 8.1 kB  00:00

**Comment by satya164** [comment]
I'll fix the installation script. Please manually install this file - http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.noarch.rpm

**Comment by ReclusiveGeek** [comment]
Sorry but that does not work 

[root@jarvis Downloads]# rpm -ivh ozon-repos-21-5.fc21.noarch.rpm 
warning: ozon-repos-21-5.fc21.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID b8c0fc22: NOKEY
Preparing...                          ################################# [100%]
	file /etc/yum.repos.d/ozonos.repo from install of ozon-repos-21-5.fc21.noarch conflicts with file from package fedy-3.2.3-7.1.noarch
[root@jarvis Downloads]#

**Comment by satya164** [comment]
Following should work, meanwhile I'll fix my mess.

```
sudo dnf erase fedy
sudo dnf install http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.noarch.rpm
sudo dnf install fedy
```

**Comment by ReclusiveGeek** [comment]
ok the erase worked no surprise there, and the install worked for ozon.

But fedy wont reinstall

Downloading Packages:
[MIRROR] fedy-4.0.0-0.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 50300 but expected size is: 50296                            
[FAILED] fedy-4.0.0-0.noarch.rpm: No more mirrors to try - All mirrors were already tried without success                                                     
Error: Error downloading packages:
  Cannot download noarch/fedy-4.0.0-0.noarch.rpm: All mirrors were tried
[root@jarvis Downloads]#

**Comment by satya164** [comment]
The error is due to wrong metadata. Try `sudo yum clean expire-cache`.

**Comment by ReclusiveGeek** [comment]
Sorry but no. 

[root@jarvis Downloads]#  yum clean expire-cache
Loaded plugins: langpacks
Cleaning repos: adobe-linux-x86_64 fedora fedora-HandBrake fedy google-chrome google-talkplugin isv_ownCloud_desktop ozonos rpmfusion-free
              : rpmfusion-free-updates rpmfusion-nonfree rpmfusion-nonfree-updates updates
0 metadata files removed
[root@jarvis Downloads]# dnf install fedy
Using metadata from Sat May 16 19:48:01 2015 (1 day, 18:45:53 hours old)
Dependencies resolved.
===============================================================================================================================================================
 Package                             Arch                                  Version                                 Repository                             Size
===============================================================================================================================================================
Installing:
 fedy                                noarch                                4.0.0-0                                 ozonos                                 49 k

Transaction Summary
===============================================================================================================================================================
Install  1 Package

Total download size: 49 k
Installed size: 135 k
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] fedy-4.0.0-0.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 50300 but expected size is: 50296                            
[FAILED] fedy-4.0.0-0.noarch.rpm: No more mirrors to try - All mirrors were already tried without success                                                     
Error: Error downloading packages:
  Cannot download noarch/fedy-4.0.0-0.noarch.rpm: All mirrors were tried

**Comment by satya164** [comment]
I'll rebuild the repo cache. Try `sudo yum install http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-0.noarch.rpm`

**Comment by satya164** [comment]
Also, I'm very much sorry about the issue :(

**Comment by ReclusiveGeek** [comment]
I have ozon installed from the rpm as you suggested .

Hay don't worry I do it from time to time. 

And I have to say Fedy really does make Fedoa desktop easy to install. So a big thank you for the project. :-)

**Comment by satya164** [comment]
@ReclusiveGeek You're welcome, and thanks :)
