### ISSUE TITLE
[Solved] Package fedy-4.0.0-0.noarch.rpm is not signed

### ISSUE THREAD

**Issue by elragnar** [satya164/fedy#165]
I 'm using fedora 21.
When I upgrade fedora there is a message like this:
"Package fedy-4.0.0-0.noarch.rpm is not signed"
and Fedy can't be executed.

I'm using this repo:
http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_21/home:satya164:fedy.repo

Any suggestion?

**Comment by satya164** [comment]
Hi. I've fixed the issue. But it will take some time to arrive due to the package cache. You can directly install the RPM for now.

```
sudo dnf install http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-1.noarch.rpm
```

**Comment by elragnar** [comment]
Hi. when I run this command:
sudo dnf install http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-1.noarch.rpm

I get an error message:
warning: /var/cache/dnf/x86_64/21/ozonos/packages/ozon-repos-21-4.fc21.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID b8c0fc22: NOKEY
Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos [Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos]

**Comment by satya164** [comment]
Try this,

```
sudo dnf install http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.noarch.rpm
sudo dnf install http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-1.noarch.rpm
```

**Comment by elragnar** [comment]
I get an error message when installing ozon-repos & fedy with dnf, but it working fine when using yum.
And now my fedy is working.
Thank you very much.

**Comment by satya164** [comment]
Yeah, DNF can act weird sometimes. Glad your issue is fixed.
