### ISSUE TITLE
Header Content-Length wrong on fedy package, cannot reinstall fedy

### ISSUE THREAD

**Issue by Jobava** [satya164/fedy#166]
trying to run the fedy script again after "yum erase fedy" and "yum update", I get this

    [MIRROR] fedy-4.0.0-0.noarch.rpm: Interrupted by header callback: Server reports Content-Length: 50300 but expected size is: 50296         
    [FAILED] fedy-4.0.0-0.noarch.rpm: No more mirrors to try - All mirrors were already tried without success                                  
    Error: Error downloading packages:
    Cannot download noarch/fedy-4.0.0-0.noarch.rpm: All mirrors were tried

**Comment by satya164** [comment]
The metadata is outdated. Can you try the following?

```
sudo yum clean expire-cache
sudo yum install fedy
```

**Comment by Jobava** [comment]
Thanks, that worked!

**Comment by satya164** [comment]
Cool :)

**Comment by banzeraaaa** [comment]
I have the same issue, I tried everything and nothing works... Could you help me? Please :)

**Comment by sudoforge** [comment]
@banzeraaaa Can you expand on "tried everything"? Have you cleaned your local cache?

**Comment by banzeraaaa** [comment]
@sudoforge Hi, thanks for the quick reply. I've already tried uninstalling and installing fedy, I've already cleaned the local cache. I tried everything I saw in the topics about bugfix and nothing works.

**Comment by sudoforge** [comment]
@banzeraaaa I'm unable to reproduce this in a Docker container:

```
[root@b755babf5f56 /]# dnf install fedy
RPM Fusion for Fedora 30 - Free - Updates                            172 kB/s | 266 kB     00:01
RPM Fusion for Fedora 30 - Free                                      478 kB/s | 735 kB     00:01
RPM Fusion for Fedora 30 - Nonfree - Updates                          44 kB/s |  40 kB     00:00
RPM Fusion for Fedora 30 - Nonfree                                   183 kB/s | 227 kB     00:01
Dependencies resolved.
=====================================================================================================
 Package                             Architecture   Version                    Repository       Size
=====================================================================================================
Installing:
 fedy                                noarch         4.8.0-1.fc30               fedy            375 k
 ...
Complete!
```

**Comment by sudoforge** [comment]
@banzeraaaa For sanity's sake, can you try running `sudo dnf clean all`, and then attempting to reinstall Fedy?
