### ISSUE TITLE
Fedy install script doesn't work on Fedora 22 RC

### ISSUE THREAD

**Issue by ahmedmagdy95** [satya164/fedy#168]
su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"
Password: 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   863  100   863    0     0   1286      0 --:--:-- --:--:-- --:--:--  1286
Adding repositories...
Last metadata expiration check performed 0:34:00 ago on Fri May 22 17:01:05 2015.
Curl error (28): Timeout was reached for http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.noarch.rpm [Connection timed out after 120001 milliseconds]
Last metadata expiration check performed 0:36:00 ago on Fri May 22 17:01:05 2015.
Status code: 404 for http://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-22.noarch.rpm
Installing fedy...
Last metadata expiration check performed 0:36:01 ago on Fri May 22 17:01:05 2015.
No package fedy available.
Error: no package matched: fedy

**Comment by satya164** [comment]
The repo was not available for Fedora 22. Now it'll work.

**Comment by ahmedmagdy95** [comment]
It still doesn't work!! 
su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer" 
Password: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   863  100   863    0     0   1656      0 --:--:-- --:--:-- --:--:--  1656
Adding repositories...
Last metadata expiration check performed 0:00:48 ago on Sat May 23 15:37:29 2015.
Status code: 404 for http://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-22.noarch.rpm
Installing fedy...
Last metadata expiration check performed 0:00:49 ago on Sat May 23 15:37:29 2015.
Error: nothing provides rpmfusion-nonfree-release needed by fedy-4.0.0-1.fc22.noarch

**Comment by satya164** [comment]
I've updated the script. it'll work now.
