### ISSUE TITLE
Fedy update fails

### ISSUE THREAD

**Issue by tadeuszjl** [satya164/fedy#169]
Current version Fedy 3.2.3
Fedora 20 on Phenom II X4

Download successful!
make: *** fedy-4.0.0: No such file or directory.  Stop.
make: *** fedy-4.0.0: No such file or directory.  Stop.
Temporary directory cleaned

**Comment by satya164** [comment]
Sorry for the inconvenience. Fedy no longer supports Fedora 20, and the inbuilt updater no longer works. Ignore it for now.

**Comment by logavanc** [comment]
I'm having the same issue in Fedora 21:

[root@megamind logavanc]# fedy
    Fedy 3.2.3 Copyright (C) 2014 Satyajit Sahoo

    This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under the terms of GNU GPL V3 or Later.

    You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>

    Verifying root access
    logavanc registered as logged in User
    Verifying minimum system requirements
    Fedora version 21 detected
    Architecture verified (64-bit)
    Internet connection verified
    Synchronizing files to /tmp/fedy
    Checking update
    Update available!
    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
    Installing update
    Downloading from: https://github.com/satya164/fedy/archive/v4.0.1.tar.gz
    Saving to: fedy.tar.gz
    --2015-05-25 15:25:14--  https://github.com/satya164/fedy/archive/v4.0.1.tar.gz
    Resolving github.com (github.com)... 192.30.252.128
    Connecting to github.com (github.com)|192.30.252.128|:443... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: https://codeload.github.com/satya164/fedy/tar.gz/v4.0.1 [following]
    --2015-05-25 15:25:15--  https://codeload.github.com/satya164/fedy/tar.gz/v4.0.1
    Resolving codeload.github.com (codeload.github.com)... 192.30.252.147
    Connecting to codeload.github.com (codeload.github.com)|192.30.252.147|:443... connected.
    HTTP request sent, awaiting response... 200 OK

        The file is already fully retrieved; nothing to do.

    Download successful!
    make: *** fedy-4.0.1: No such file or directory.  Stop.
    make: *** fedy-4.0.1: No such file or directory.  Stop.
    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
    Temporary directory cleaned
    [root@megamind logavanc]#

**Comment by satya164** [comment]
@logavanc update Fedy via yum.
