### ISSUE TITLE
Suggestion : Replace Older Kingsoft office with WPS office.

### ISSUE THREAD

**Issue by Abhinav1217** [satya164/fedy#173]
Kingsoft office is stopped being developed and is now being developed as WPS office 
> On June 6, 2014, Kingsoft Office has been changed to WPS Office. All Kingsoft Office products, both paid and free, have been changed to WPS Office. 
> [Wikipedia](http://en.wikipedia.org/wiki/WPS_Office#Today)

I realised this when it failed to install Kingsoft office on my Fedora 21 repetitively. I googled  for problem and found out about the change. Kingsoft office installation failed for several dependency issues, It required older version of many packages .

I installed WPS Office using this link http://wps-community.org/download.html . It contains rpm, deb, and tar.gz . I used the x86_64  rpm.  

Unless there is a specific reason for Fedy to list Kingsoft Office, I think it should be replaced with WPS office. Or at least WPS office should be availble as option , Like you have both sublime text 2 and 3 in option. 

Referance:
http://en.wikipedia.org/wiki/WPS_Office
http://wps.com/linux/
http://wps-community.org/download.html

**Comment by satya164** [comment]
Thanks. Will change that.

**Comment by gitgt** [comment]
[F22 x64] WPS install error with fedy-3.2.1.

**Comment by gitgt** [comment]
Error also with the current Fedy from Git.
