### ISSUE TITLE
Numix themes no longer a part of fedy?

### ISSUE THREAD

**Issue by Jobava** [satya164/fedy#174]
So Numix is no longer a part of fedy? Any other theme packs you plan to include in the near future?

Numix icons and window themes are nicer and the default top bar is thinner, which is nice.

**Comment by satya164** [comment]
We're working on a new repo for Numix themes after which we'll add them back to fedy.

**Comment by metabsd** [comment]
numix is plan to get back ?

**Comment by satya164** [comment]
@metabsd I'm setting up the repo. It'll be available soon.
