### ISSUE TITLE
Suggestion: Add copr search and install 

### ISSUE THREAD

**Issue by PhnxRbrn** [satya164/fedy#177]
Is there any possibility of adding functionality to search fedora copr, then install the repo and application?

**Comment by satya164** [comment]
Fedy itself cannot support these kind of tasks, as plugins don't have any UI. While it should be possible to make a new application for this, and copr provides an API, people make lots of test repos on copr too, which means you'll not always get what you want, or may get broken repos.

While I'm not saying that I won't do something for this in future, technically Fedy cannot support such a thing, so Fedy will never have this feature.
