### ISSUE TITLE
TeamViewer doesn't work

### ISSUE THREAD

**Issue by romu70** [satya164/fedy#181]
If I try to run it in a terminal, it stays locked on "launching...".

**Comment by headbite** [comment]
The download location changed. For now just type this into the terminal and it will update to the latest version which works on F22. I'm not comfortable doing commits yet so someone else will have to pick this up.
su -c 'dnf -y install http://www.teamviewer.com/download/teamviewer.i686.rpm'

**Comment by romu70** [comment]
No guys, the issue is still here, terminal is locked on "Launching TeamViewer ...". And nothing more.

**Comment by satya164** [comment]
@romu70 run `sudo dnf -y install http://www.teamviewer.com/download/teamviewer.i686.rpm` and it'll start working.

**Comment by romu70** [comment]
Thanks @satya164 , this way is works.
