### ISSUE TITLE
install script fails on fedora 22

### ISSUE THREAD

**Issue by yafp** [satya164/fedy#182]
If i do execute the fedy-installer script i do get the following output

Adding repositories...
Installing fedy...
Waiting for process with pid 20016 to finish.
Last metadata expiration check performed 0:00:02 ago on Fri May 29 20:12:51 2015.
Kein Paket fedy verfügbar. (translated: no package fedy available)
Fehler: no package matched: fedy

Any idea what i am doing wrong?

**Comment by satya164** [comment]
Might be a cache issue. Try running `dnf clean expire-cache`.

**Comment by yafp** [comment]
No change

**Comment by pyrignis** [comment]
Same issue for me.
`dnf clean expire-cache` did not solve it neither.

**Comment by benny215** [comment]
Same issue after f22 upgrade, but not after clean install. To get it working I just manually installed repo file from Ozon's website: http://goodies.ozon-os.com/repo/22/noarch/ozon-repos-22-5.fc22.noarch.rpm

After that Fedy installed and ran no problem.

**Comment by yafp** [comment]
i can confirm what @benny215 mentioned.
On an upgraded f22 install - manually installing ozon-repos-22-5.fc22.noarch.rpm was the requirements to run the fedy_installer script successfully afterwards.

Thanks for the pointer

@satya164 
Should i close the issue?
