### ISSUE TITLE
Fail in Brackets, Steam and libdvdcss installation

### ISSUE THREAD

**Issue by henriquepicanco** [satya164/fedy#184]
I tried to install Brackets, Steam and libdvdcss by Fedy last night, but received an installation error, saying only that the installation had failed.

I make that on Fedora 22 - KDE Spin

When I make that with Terminal opened:

[henrique@fedora-twentytwo ~]$ fedy
Repository successfully enabled.
Failed to synchronize cache for repo 'livna' from 'http://rpm.livna.org/mirrorlist': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'jgillich-brackets' from 'https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-22-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 3:58:43 ago on Sat May 30 14:53:13 2015.
Nenhum pacote brackets disponível. <<-- "brackets" is not available for installation
Error: no package matched: brackets
Failed to synchronize cache for repo 'livna' from 'http://rpm.livna.org/mirrorlist': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'jgillich-brackets' from 'https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-22-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 4:02:05 ago on Sat May 30 14:53:13 2015.
Nenhum pacote steam disponível. <-- "steam" is not available for installation
Error: no package matched: steam

**Comment by Abhinav1217** [comment]
I too am getting same problem. I didnt try to install steam but I tried to install Brackets and libdvdcss using fedy, here's the output on terminal.
```
[root@abhinav-fed22 Abhinav] $ fedy
Repository successfully enabled.
Failed to synchronize cache for repo 'livna' from 'http://rpm.livna.org/mirrorlist': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'Dropbox' from 'http://linux.dropbox.com/fedora/22/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'jgillich-brackets' from 'https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-22-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 0:11:25 ago on Tue Jun  2 07:18:10 2015.
No package brackets available.
Error: no package matched: brackets
Failed to show notification: The connection is closed
Failed to synchronize cache for repo 'livna' from 'http://rpm.livna.org/mirrorlist': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'Dropbox' from 'http://linux.dropbox.com/fedora/22/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'jgillich-brackets' from 'https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-22-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 0:11:33 ago on Tue Jun  2 07:18:10 2015.
Package livna-release-1:1-1.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
Failed to synchronize cache for repo 'livna' from 'http://rpm.livna.org/mirrorlist': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'Dropbox' from 'http://linux.dropbox.com/fedora/22/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'jgillich-brackets' from 'https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-22-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 0:11:42 ago on Tue Jun  2 07:18:10 2015.
Dependencies resolved.
================================================================================
 Package           Arch           Version                  Repository      Size
================================================================================
Installing:
 libdvdcss         x86_64         1.3.99-1.fc22            ozonos          69 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 69 k
Installed size: 172 k
Downloading Packages:
libdvdcss-1.3.99-1.fc22.x86_64.rpm               81 kB/s |  69 kB     00:00    
--------------------------------------------------------------------------------
Total                                            81 kB/s |  69 kB     00:00     
warning: /var/cache/dnf/x86_64/22/ozonos/packages/libdvdcss-1.3.99-1.fc22.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 73edaa09: NOKEY
GPG key at file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos (0xB8C0FC22) is already installed
Error: The GPG keys listed for the "Repository for Ozon OS" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: libdvdcss-1.3.99-1.fc22.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos

Failed to show notification: The connection is closed
[root@abhinav-fed22 Abhinav] $ 
```

**Comment by satya164** [comment]
`sudo dnf clean metadata` should fix the `libdvdcss` issue.

**Comment by sanyer** [comment]
Was able to install Steam using this repo http://negativo17.org/steam/

**Comment by satya164** [comment]
The negativo17 repo didn't work for me. There were package conflicts. But I have added it, just in case.

**Comment by BloodRose86** [comment]
Hi there sorry but the fedy does not work at all for fedora 22 please help :(:(:(

**Comment by satya164** [comment]
@BloodRose86 Fedy repo had a downtime. Can you try again?

**Comment by BloodRose86** [comment]
Hi thanks for the come back but still no luck
bash -c 'su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   911  100   911    0     0    736      0  0:00:01  0:00:01 --:--:--   736
Adding repositories...
Installing fedy...
Last metadata expiration check performed 0:57:55 ago on Sat Jul 25 12:58:47 2015.
No package fedy available.
Error: no package matched: fedy

**Comment by BloodRose86** [comment]
i even have probs with rawhide to install

i really dont know what the heck is going on.

**Comment by satya164** [comment]
Rawhide repos are not available for Fedy.
