### ISSUE TITLE
GPG key error for ozonos repo

### ISSUE THREAD

**Issue by Jobava** [satya164/fedy#185]
When trying to update, I get the following error:

warning: /var/cache/yum/x86_64/21/ozonos/packages/libdvdcss-1.3.0-1.fc21.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 73edaa09: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos

The GPG keys listed for the "Repository for Ozon OS" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: libdvdcss-1.3.0-1.fc21.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos

**Comment by satya164** [comment]
Hi. Try doing the following,

`sudo dnf clean metadata`

**Comment by Jobava** [comment]
Thanks, that worked!
