### ISSUE TITLE
Need Fedora 22 repo xml

### ISSUE THREAD

**Issue by testman42** [satya164/fedy#186]
Every time I run "dnf update, i get this:
>Failed to synchronize cache for repo 'fedy' from 'http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_22/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.

Probably because Fedora 22 directory is missing here: http://download.opensuse.org/repositories/home:/satya164:/fedy/

That is not a major issue, but it is annoying to see error every time repos update.

**Comment by satya164** [comment]
Hi. Please delete the repo file since we've moded to Ozon repo. Use the installation script to add the new repo and install Fedy.
