### ISSUE TITLE
Suggestion: Add Intellij Idea Community Edition

### ISSUE THREAD

**Issue by PhnxRbrn** [satya164/fedy#188]
Could you add Intellij Idea Community Edition to the possible applications to be installed by fedy?

**Comment by satya164** [comment]
I don't have enough time to do it. Pull requests are welcome.

**Comment by PhnxRbrn** [comment]
There are now two IntelliJ Idea Community Editions within the plugins. One of them should be removed.

**Comment by satya164** [comment]
@PhnxRbrn Done.
