### ISSUE TITLE
fedy not found 

### ISSUE THREAD

**Issue by 230v** [satya164/fedy#216]
su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"
Пароль: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   906  100   906    0     0    855      0  0:00:01  0:00:01 --:--:--   857
Adding repositories...
Russian Fedora for Fedora 21 - Nonfree - Updates                                     27 kB/s | 7.6 kB     00:00    
RPM Fusion for Fedora 21 - Free - Updates                                            99 kB/s | 383 kB     00:03    
RPM Fusion for Fedora 21 - Nonfree - Updates                                         88 kB/s | 160 kB     00:01    
RPM Fusion for Fedora 21 - Free                                                     100 kB/s | 465 kB     00:04    
Fedora 21 - i386 - Updates                                                          105 kB/s |  20 MB     03:12    
Russian Fedora for Fedora 21 - Free - Updates                                        71 kB/s |  47 kB     00:00    
Russian Fedora for Fedora 21 - Fixes                                                 57 kB/s |  26 kB     00:00    
Russian Fedora for Fedora 21 - Free                                                  95 kB/s | 207 kB     00:02    
RPM Fusion for Fedora 21 - Nonfree                                                   92 kB/s | 171 kB     00:01    
Russian Fedora for Fedora 21 - Branding - Updates                                   3.1 kB/s | 1.0 kB     00:00    
Russian Fedora for Fedora 21 - Fixes - Updates                                       33 kB/s |  10 kB     00:00    
Russian Fedora for Fedora 21 - Branding                                              68 kB/s |  43 kB     00:00    
Using metadata from Sun Jun 21 15:04:29 2015 (0:40:57 hours old)
Status code: 404 for http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.R.noarch.rpm
Installing fedy...
Using metadata from Sun Jun 21 15:04:29 2015 (0:41:06 hours old)
Пакета с названием fedy не найдено.
Ошибка: no package matched: fedy

**Comment by satya164** [comment]
That's weird. Seems that the output of `rpm -E %dist` on your machine has an extra `.R`, may be because of the russian Fedora repo?

Anyways, try the script again. It should work now.

**Comment by 230v** [comment]
I disable RF repo, but fedy not found. Installed old version from opensuse repo, thats work, but requests for update.
