### ISSUE TITLE
Can not install fedy from fedy-installer

### ISSUE THREAD

**Issue by m0zgen** [satya164/fedy#218]
Hi, I tying using fedy installer script, after run show text:
```
Adding repositories...
Status code: 404 for http://goodies.ozon-os.com/repo/20/noarch/ozon-repos-20-5.fc20.noarch.rpm
Installing fedy...
No package fedy available.
Error: Nothing to do.
```

I use Fedora 20, this repo not available on ozon, how I can run or install Fedy in my Fedora?

P.S. Sorry my eng in bad

**Comment by Jobava** [comment]
Fedora 20 support stops on June 24th this year. You should consider upgrading to F21 or F22.

**Comment by m0zgen** [comment]
Sadly, thank you for reply :)

**Comment by 230v** [comment]
Привет, ставь отсюда http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_21/noarch/

**Comment by m0zgen** [comment]
Привет, спасибо, запускается и работет, единственно после установки предлагает обновиться, чего делать не надо ))
