### ISSUE TITLE
Getting syntax errors on Fedora 22

### ISSUE THREAD

**Issue by RomanSC** [satya164/fedy#237]
I'm getting this when I attempt to install on Fedora 22, I'm not sure if it's a bug:

     [root@localhost Downloads]# curl https://satya164.github.io/fedy/fedy-isntaller -o fedy-installer
       % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                      Dload  Upload   Total   Spent    Left  Speed
     100  9340  100  9340    0     0  28275      0 --:--:-- --:--:-- --:--:-- 28303
     [root@localhost Downloads]# chmod +x fedy-installer
     [root@localhost Downloads]# sudo ./fedy-installer
     ./fedy-installer: line 1: syntax error near unexpected token `newline'
     ./fedy-installer: line 1: `<!DOCTYPE html>'
     [root@localhost Downloads]#

**Comment by RomanSC** [comment]
Looks like my issues were caused by fish user shell (fishshell.com). It's now installing just fine. Thanks for developing this!

**Comment by azmanov** [comment]
Linux Noob here with the same problem, so forgive me if I say something really dumb. 

I am using the default shell, and getting the exact same "syntax error" etc message. How did you fix it?

**Comment by DStewart1997** [comment]
@azmanov How are you installing it? Are you using the command found on [folkswithhats.org](http://folkswithhats.org/)?

    bash -c 'su -c "curl http://folkswithhats.org/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"

**Comment by azmanov** [comment]
Tried that and it worked! I had previously used

`su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"` 

I guess that is the old way. Thanks

**Comment by DStewart1997** [comment]
@azmanov Yeah, the website in that command ([satya164.github.io](https://satya164.github.io/)) isn't used anymore - it is now [folkswithhats.org](http://folkswithhats.org/).
