### ISSUE TITLE
Change install script to work with different shells

### ISSUE THREAD

**Issue by greendragon2010** [satya164/fedy#238]
Could we add bash -c to the install command so it would read
```bash
'bash -c su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer" '
```
so that people who change their shells to fish or other non-bash compatible shells the command will still work properly and they won't run into issue.

I saw a reddit user have this [problem](https://www.reddit.com/r/Fedora/comments/3dx678/how_do_i_install_fedy_on_fedora_22/), and wanted to fix it upstream.

**Comment by satya164** [comment]
Feel free to send a pull request.

**Comment by greendragon2010** [comment]
Where is the install script located? I will gladly send a pull request if I can find the install script to adjust it.

**Comment by satya164** [comment]
@greendragon2010 It's in the `gh-pages` branch.

**Comment by greendragon2010** [comment]
@satya164  Thanks pull request created.
