### ISSUE TITLE
ozon-os.com repos server down?

### ISSUE THREAD

**Issue by irus6** [satya164/fedy#240]
I can't install fedy.

**Comment by FlorianLudwig** [comment]
Yes, looks down here too :(

**Comment by irus6** [comment]
pls, fix it.

**Comment by FlorianLudwig** [comment]
this is up to the guys from ozon os. i guess. https://github.com/ozonos

**Comment by wilfm** [comment]
Have the issue here as well (server seems down) . Had to disable the  `/etc/yum.repos.d/ozonos.repo.`. Have they changed their hosting to http://ozonos.github.io/ and https://sourceforge.net/projects/ozonosos or something?

**Comment by mstallmo** [comment]
Down for me as well. I keep receiving a curl error and the connection times out.

**Comment by boussaffawalid** [comment]
same thing here

**Comment by ulcango** [comment]
same thing here.

**Comment by Quanttek** [comment]
Still down

**Comment by KardiWeb** [comment]
repository is dead? new repository?

**Comment by thndgonz** [comment]
If you need to install Fedy you could 

`cd ~; sudo dnf install git -y; git clone https://github.com/satya164/fedy.git; cd fedy`
`sudo ./fedy` 
install the software/tweaks you need. 

Pretty much what I did, works well so far. Let's hope the issue is resolved soon.

**Comment by satya164** [comment]
It's up now.

**Comment by wilfm** [comment]
https://github.com/folkswithhats/fedy/issues/262 - may be happening again...

**Comment by fnkr** [comment]
Still not working for me. How to fix this?

```
Failed to synchronize cache for repo 'ozonos' from 'http://goodies.ozon-os.com/repo/22/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
```

**Comment by satya164** [comment]
@fnkr Please remove the ozonos repo and use the install script at http://folkswithhats.org

**Comment by fnkr** [comment]
@satya164 Thanks, that worked!
