### ISSUE TITLE
[F22] authentication failure 

### ISSUE THREAD

**Issue by Minayev** [satya164/fedy#247]
As the title suggests, I'm unable to authenticate installs and tweaks. Tried both login and root password with text shown to no avail. Please help!

**Comment by satya164** [comment]
@Minayev Fixed?

**Comment by Minayev** [comment]
Yeah. Turns out installing fedy did the same problem to software center (authentication failure on installing softwares). Restarts didn't help, but putting my laptop to sleep and woke it up magically fixed everything. Lol
That aside, fedy helps me immensely, great job and thank you!
