### ISSUE TITLE
Suggestion : PeaZip

### ISSUE THREAD

**Issue by Abhinav1217** [satya164/fedy#90]
Hi,
Can you include [PeaZip](http://peazip.sourceforge.net/) in your software collections. They do provide RPM binaries but I am having hard time resolving dependencies on my F20 64 bit system.  It is free software not included in fedora repo, Easy to use interface which windows migrated persons like me would like to see on Linux.

**Comment by satya164** [comment]
How is PeaZip better than file-roller which is well integrated with nautilus?
